<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'ZucchiDoctrine\Module'                                    => __DIR__ . '//Module.php',
    'ZucchiDoctrine\Event\DoctrineListener'                    => __DIR__ . '//src/ZucchiDoctrine/Event/DoctrineListener.php',
    'ZucchiDoctrine\Hydrator\DoctrineEntity'                   => __DIR__ . '//src/ZucchiDoctrine/Hydrator/DoctrineEntity.php',
    'ZucchiDoctrine\Entity\ChangeTrackingTrait'                => __DIR__ . '//src/ZucchiDoctrine/Entity/ChangeTrackingTrait.php',
    'ZucchiDoctrine\Entity\AbstractEntity'                     => __DIR__ . '//src/ZucchiDoctrine/Entity/AbstractEntity.php',
    'ZucchiDoctrine\Service\AbstractService'                   => __DIR__ . '//src/ZucchiDoctrine/Service/AbstractService.php',
    'ZucchiDoctrine\Datatype\DateTimeTzType'                   => __DIR__ . '//src/ZucchiDoctrine/Datatype/DateTimeTzType.php',
    'ZucchiDoctrine\Datatype\MoneyType'                        => __DIR__ . '//src/ZucchiDoctrine/Datatype/MoneyType.php',
    'ZucchiDoctrine\Datatype\DateType'                         => __DIR__ . '//src/ZucchiDoctrine/Datatype/DateType.php',
    'ZucchiDoctrine\Datatype\TimeType'                         => __DIR__ . '//src/ZucchiDoctrine/Datatype/TimeType.php',
    'ZucchiDoctrine\Datatype\DateTimeType'                     => __DIR__ . '//src/ZucchiDoctrine/Datatype/DateTimeType.php',
    'ZucchiDoctrine\EntityManager\EntityManagerAwareInterface' => __DIR__ . '//src/ZucchiDoctrine/EntityManager/EntityManagerAwareInterface.php',
    'ZucchiDoctrine\EntityManager\EntityManagerAwareTrait'     => __DIR__ . '//src/ZucchiDoctrine/EntityManager/EntityManagerAwareTrait.php',
    'ZucchiDoctrine\Query\Mysql\Regexp'                        => __DIR__ . '//src/ZucchiDoctrine/Query/Mysql/Regexp.php',
    'ZucchiDoctrine\Behavior\Timestampable\TimestampableTrait' => __DIR__ . '//src/ZucchiDoctrine/Behavior/Timestampable/TimestampableTrait.php',
    'ZucchiDoctrine\Form\Annotation\OneToMany'                 => __DIR__ . '//src/ZucchiDoctrine/Form/Annotation/OneToMany.php',
    'ZucchiDoctrine\View\Helper\EntityField'                   => __DIR__ . '//src/ZucchiDoctrine/View/Helper/EntityField.php',
);